<?php

namespace ContainerXxLNCZy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored__ServiceLocator_MExgntV_ExceptionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.mExgntV.Exception' shared service.
     *
     * @return \Exception
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.mExgntV": it references class "Exception" but no such service exists.');
    }
}
