<?php

namespace ContainerXxLNCZy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MExgntVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mExgntV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mExgntV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'exception' => ['privates', '.errored..service_locator.mExgntV.Exception', NULL, 'Cannot autowire service ".service_locator.mExgntV": it references class "Exception" but no such service exists.'],
        ], [
            'exception' => 'Exception',
        ]);
    }
}
