<?php

namespace ContainerXxLNCZy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppCacheWarmerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Cache\AppCacheWarmer' shared autowired service.
     *
     * @return \App\Cache\AppCacheWarmer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Cache/AppCacheWarmer.php';

        return $container->privates['App\\Cache\\AppCacheWarmer'] = new \App\Cache\AppCacheWarmer(($container->privates['App\\Service\\ClientFactory'] ?? $container->getClientFactoryService()), ($container->services['cache.app'] ?? $container->getCache_AppService()));
    }
}
