<?php

namespace ContainerXxLNCZy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSettingsTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\SettingsType' shared autowired service.
     *
     * @return \App\Form\Type\SettingsType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/SettingsType.php';

        return $container->privates['App\\Form\\Type\\SettingsType'] = new \App\Form\Type\SettingsType();
    }
}
