<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ4Zx9zr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ4Zx9zr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ4Zx9zr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ4Zx9zr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ4Zx9zr\App_KernelDevDebugContainer([
    'container.build_hash' => 'J4Zx9zr',
    'container.build_id' => '4782dd9e',
    'container.build_time' => 1660119592,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ4Zx9zr');
