<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], [], []],
    'courses' => [[], ['tab' => 'courses', '_controller' => 'App\\Controller\\CoursesController'], [], [['text', '/courses']], [], [], []],
    'categories' => [[], ['permanent' => true, 'route' => 'courses', 'keepQueryParams' => true, '_controller' => 'Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::redirectAction'], [], [['text', '/courses/categories']], [], [], []],
    'category' => [['categorySlug'], ['tab' => 'courses', '_controller' => 'App\\Controller\\CoursesController'], [], [['variable', '/', '[^/]++', 'categorySlug'], ['text', '/courses/categories']], [], [], []],
    'course' => [['courseSlug'], ['tab' => 'courses', '_controller' => 'App\\Controller\\CourseController'], [], [['variable', '/', '[^/]++', 'courseSlug'], ['text', '/courses']], [], [], []],
    'lessons' => [['courseSlug'], ['permanent' => true, 'route' => 'course', 'keepQueryParams' => true, '_controller' => 'Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::redirectAction'], [], [['text', '/lessons'], ['variable', '/', '[^/]++', 'courseSlug'], ['text', '/courses']], [], [], []],
    'lesson' => [['courseSlug', 'lessonSlug'], ['tab' => 'courses', '_controller' => 'App\\Controller\\LessonController'], [], [['variable', '/', '[^/]++', 'lessonSlug'], ['text', '/lessons'], ['variable', '/', '[^/]++', 'courseSlug'], ['text', '/courses']], [], [], []],
    'reset' => [[], ['_controller' => 'App\\Controller\\ResetController'], [], [['text', '/settings/reset']], [], [], []],
    'settings' => [[], ['_controller' => 'App\\Controller\\SettingsController'], [], [['text', '/settings']], [], [], []],
    'imprint' => [[], ['_controller' => 'App\\Controller\\ImprintController'], [], [['text', '/imprint']], [], [], []],
    'landing_page' => [[], ['tab' => 'home', '_controller' => 'App\\Controller\\LandingPageController'], [], [['text', '/']], [], [], []],
    'not_found' => [['anything'], ['_controller' => 'App\\Controller\\NotFoundController'], ['anything' => '.+'], [['variable', '/', '.+', 'anything']], [], [], []],
];
